### ISSUE TITLE
Create shopping cart page

### ISSUE THREAD

**Issue by oskarprzybylski23** [fac29/hoda-e-commerce-frontend#7]

**Comment by halimahexe** [comment]
Just to note, the shopping cart page is reading the wrong product IDs at the moment.

![Image](https://github.com/fac29/hoda-e-commerce-frontend/assets/127022084/4d41a010-de1e-4d2a-bf3e-f1d2ad664af2)
![Image](https://github.com/fac29/hoda-e-commerce-frontend/assets/127022084/d9f80012-34d2-435a-997b-e2b2145617e0)
